### ISSUE TITLE
 Merge netcdf4 files: same variables, different time series (PyNCO)

### ISSUE THREAD

**Issue by czender** [nco/pynco#12]
(PyNCO question posted on behalf of a user who does not know about github and PyNCO)

Hi,
I am trying to merge netcdf4 files that have the same variables within the files but different time series. I have downloaded the NCO package and trying to merge the files using ncrcat. I am using spyder(python) to read the netcdf4 files. I have done the following but then am confused as to how to write the command.

```
from nco import Nco
nco = Nco()

from netCDF4 import Dataset

file4 = Dataset('C:/test4.nc4')
file3 = Dataset('C:/test3.nc4')
```

I know that in order to combine the 2 files, ncrcat must be used in such a manner:
`ncrat file1.nc file2.nc fileoutput.nc`

but I am unsure of how to execute this command based on my input files. Any assistance on this matter would be greatly appreciated.
Kind regards,
Tasha

**Comment by jhamman** [comment]
I think it would be `nco.ncrcat(input=['C:/test4.nc4', 'C:/test3.nc4'], output='fileoutput.nc')`.  

I see you are using windows, just fyi, I haven't tested PyNCO on windows at all so don't be suprised if somethings don't work :wink:
