### ISSUE TITLE
Conda-forge instead of ioos?

### ISSUE THREAD

**Issue by czender** [nco/pynco#20]
Is the ioos channel that PyNCO uses completely compatible with conda-forge or might it cause path/library issues? Does it make sense to shift PyNCO from ioos to conda-forge?  I'm hazy on the details of compatibility between conda-forge and ioos channels. 

The conda-forge NCO package was recently (~April) updated to include ESMF_RegridWeightGen for use by ncremap. This makes the conda-forge package very appealing, and it would seem make sense to have both NCO and PyNCO on the same channel...

**Comment by ocefpaf** [comment]
As the maintainer of both `conda-forge` and `ioos` I highly recommend changing everything to `conda-forge`. The `ioos`channel is deprecated and may be removed at any time. (I keep it only for experimentation and should not be used on production.)

**Comment by jhamman** [comment]
closed via 99915b6aece9a1fe1e5f2207bd532d944153793f
