### ISSUE TITLE
concatenating variables from multiple netCDF files does not work

### ISSUE THREAD

**Issue by Yefee** [nco/pynco#21]
Hi, Joe

Recently, I found pynco and tried it in my work. But It seems nco.ncrcat does not work properly. 

```
infile = glob.glob('b.e13.Bi1850C5.f19_g16.21ka.06.test.cam.h0.026*.nc')
nco.ncrcat(input=infile,output="TS.nc",v="TS",debug=True)
```

No TS.nc file was created.
Any suggestions?

**Comment by hmb1** [comment]
Hi Yefee,
 there has recently been quite a few changes.
 nco.ncrcat () work for me.  
Can you please post the error messages you are getting ?  
Are they from python or ncrcat ?
...Henry

**Comment by Yefee** [comment]
Hi, Henry

No error came out, no output file either.
If I didnt specify the variable, TS, it can concatenate all variables in the nc file without mistakes.
Could you try to concatenate a single variable?
 
Yeah, they are in python.

CF

**Comment by hmb1** [comment]
try running pynco with debug on. 
do: 
 use the constructor below - before running ncrcat
 nco = Nco(debug=True)

**Comment by jhamman** [comment]
@Yefee - I hope you were able to sort this out.  Please reopen if you have outstanding questions here.
