### ISSUE TITLE
outputOperators with multiple meanings

### ISSUE THREAD

**Issue by lizaclark** [nco/pynco#22]
Since NCO version 4.3.7, output operators `-H`, `-M`, and `-m` have dual meanings depending on whether or not `-A` is specified. "When copying/subsetting/appending files (as opposed to printing them), the copying of data, variable metadata, and global/group metadata are now turned OFF by -H, -m, and -M, respectively." (https://sourceforge.net/p/nco/discussion/9830/thread/0fdc1d1e/).

However, `pynco` checks for these output operators to determine whether the output prints out to the screen [lines 208-212](https://github.com/nco/pynco/blob/master/nco/nco.py#L208-L212). In that case, the output file is not appended to the `cmd` before the function `call` at [line 215](https://github.com/nco/pynco/blob/master/nco/nco.py#L215). The result is that the `-A` flag and its alternate uses are ignored. This can be fixed by adding a check for `-A` in the definition of `operatorPrintsOut` in lines 208-212.

**Comment by czender** [comment]
Thank you for the patch. We will let @jhamman decide whether to merge. If we havn't merged within a week or two, please ping me and @hmb1 by responding here.

**Comment by hmb1** [comment]
Hi Liza,
 many thanks for the patch -- please test as soon as joe does the merge
...Henry

**Comment by jhamman** [comment]
closed via #24 (see also #23)
