### ISSUE TITLE
Pip install incomplete

### ISSUE THREAD

**Issue by braaannigan** [nco/pynco#25]
Hi

I tried to get nco.ncatted working where I installed the package using pip but it didn't work.  I've set out how I fixed it below and what needs to be done to solve the issue generally.

Firstly, the pip install didn't include the custom.py file, so python didn't recognise the c.Atted object in this command: nco.ncatted(input="in.nc" options=[ c.atted("overwrite","_FillValue","three_dmn",-9.91e+33,'d')])     

Once I added the custom.py file to my nco folder the command still didn't work.  The github code seemed to have extra stuff around line 102, so I replaced the pip file with the github file and everything worked perfectly.

Can someone: add the custom.py file to the pip package; update the pip package to the new github nco.py file; and add the line 'from nco import custom as c' to the user instructions on https://github.com/nco/pynco

Thanks for building the package!
Liam

**Comment by jhamman** [comment]
@braaannigan - 

That feature hasn't made it into a release just yet. Once we get #23 and #24 sorted out, we'll update the pypi repo.

**Comment by braaannigan** [comment]
Great, thanks for your efforts!

**Comment by jhamman** [comment]
I'll be issuing a new pypi release tonight.
