### ISSUE TITLE
c.Rename not defined

### ISSUE THREAD

**Issue by iMarang** [nco/pynco#30]
Hi,

I'm trying to rename all vars and dims in a set of netcdf files and wanted to use Python to achieve this.  I found pynco and used your sample code for renaming.

```Python
os.chdir('/g/data/rr9/IM_PhD/data/test_download/latlon_fix/MU-CLIM/')

nco = pynco.Nco()
rDict = {
    'latitude': 'lat',
    'longitude': 'lon'
}
for fname in glob('*.nc'):
    nco.ncrename(input=fname, options=[ c.Rename("variable", rDict) ])
```

However it comes up a 'NameError: name 'c' is not defined'.  I'm not a Python guru so thought my code might be off, but can you confirm?  The docs make no mention of defining a 'c' object.

Cheers
Ian

**Comment by hmb1** [comment]
Hi Ian,
try dropping the 'c.' in the options.
i.e:  
`nco.ncrename(input=fname, options=[ Rename("variable", rDict) ])`

...Henry

**Comment by hmb1** [comment]
Sorry Ian,
 in my test script i had the following import
`from custom import Atted,Limit,LimitSingle,Rename`

**Comment by iMarang** [comment]
Hi Henry,

Thanks for getting back to me.

After reinstall the command Rename is found, but now I have a new error:

TypeError                                 Traceback (most recent call last)
<ipython-input-11-6f39dd6a8b94> in <module>()
      7 }
      8 for fname in glob('*.nc'):
----> 9     nco.ncrename(input=fname, options=[ Rename("variable", rDict) ])

/g/data/rr9/IM_PhD/projects/xa5/anaconda/lib/python2.7/site-packages/nco/nco.pyc
in get(self, input, **kwargs)
    238                 self.stdout = retvals["stdout"]
    239                 self.stderr = retvals["stderr"]
--> 240                 if not self.hasError(method_name, input, cmd,
retvals):
    241                     return retvals["stdout"]
    242                     # parsing can be done by 3rd party

/g/data/rr9/IM_PhD/projects/xa5/anaconda/lib/python2.7/site-packages/nco/nco.pyc
in call(self, cmd, inputs, environment)
    100             print('# DEBUG
==================================================')
    101             if environment:
--> 102                 for key, val in list(environment.items()):
    103                     print("# DEBUG: ENV: {0} = {1}".format(key,
val))
    104             print('# DEBUG: CALL>> {0}'.format('
'.join(inline_cmd)))

TypeError: sequence item 1: expected string, Rename found

This is from exactly the same script as before but with the c dropped:

for fname in glob('*.nc'):
    nco.ncrename(input=fname, options=[ Rename("variable", rDict) ])

Any ideas?

Cheers
Ian

**Comment by hmb1** [comment]
Hi Ian,
am unable to recreate your error above.
for now can please try with debug switched on that's in the following line:
`nco = pynco.Nco(debug=True)`

 ...Henry

**Comment by iMarang** [comment]
Hi Henry,

Sorry for the delay in getting back to you.  I've run it with the 'debug=True' in the nco class instantiation and here's the result:

# DEBUG ==================================================
# DEBUG: CALL>> ncrename --help
# DEBUG ==================================================
Found method: ncrename
# DEBUG ==================================================
# DEBUG: CALL>> /g/data/rr9/IM_PhD/projects/xa5/anaconda/bin/ncrename -v "latitude","lat" -v "longitude","lon" --nco_dbg_lvl=3 MU-CLIM_WRF3-3-ERAInterim_rainfall-amount_hourly_05deg-SWWA_1981-2009_00000000_200711.nc
# DEBUG ==================================================
# DEBUG: RETURNCODE: 0
# DEBUG ==================================================
# DEBUG: CALL>> /g/data/rr9/IM_PhD/projects/xa5/anaconda/bin/ncrename -v "latitude","lat" -v "longitude","lon" --nco_dbg_lvl=3 MU-CLIM_WRF3-3-ERAInterim_rainfall-amount_hourly_05deg-SWWA_1981-2009_00000000_200712.nc
# DEBUG ==================================================
# DEBUG: RETURNCODE: 1
Error in calling operator ncrename with:
>>> /g/data/rr9/IM_PhD/projects/xa5/anaconda/bin/ncrename -v "latitude","lat" -v "longitude","lon" --nco_dbg_lvl=3 MU-CLIM_WRF3-3-ERAInterim_rainfall-amount_hourly_05deg-SWWA_1981-2009_00000000_200712.nc <<<
Inputs: MU-CLIM_WRF3-3-ERAInterim_rainfall-amount_hourly_05deg-SWWA_1981-2009_00000000_200712.nc
ncrename: INFO Extended filetype of MU-CLIM_WRF3-3-ERAInterim_rainfall-amount_hourly_05deg-SWWA_1981-2009_00000000_200712.nc is NC_FORMAT_HDF5, mode = 4097
ncrename: TIMER Metadata setup and file layout before main loop took    0.01 s
ncrename: CONVENTION File "Conventions" attribute is "CF-1.6"
ncrename: WARNING "coordinates" attribute for variable /rainfall_amount is type NC_STRING, not NC_CHAR. This violates CF convention for specifying additional attributes. Therefore will skip this attribute. If you want CF to support NC_STRING attributes, please tell them and CC: NCO.
ncrename: WARNING "coordinates" attribute for variable /landmask is type NC_STRING, not NC_CHAR. This violates CF convention for specifying additional attributes. Therefore will skip this attribute. If you want CF to support NC_STRING attributes, please tell them and CC: NCO.
ncrename: WARNING "grid_mapping" attribute for variable /rainfall_amount is type NC_STRING, not NC_CHAR. This violates CF convention for specifying additional attributes. Therefore will skip this attribute. If you want CF to support NC_STRING attributes, please tell them and CC: NCO.
ncrename: WARNING "coordinates" attribute for variable /rainfall_amount is type NC_STRING, not NC_CHAR. This violates CF convention for specifying additional attributes. Therefore will skip this attribute. If you want CF to support NC_STRING attributes, please tell them and CC: NCO.
ncrename: WARNING "coordinates" attribute for variable /landmask is type NC_STRING, not NC_CHAR. This violates CF convention for specifying additional attributes. Therefore will skip this attribute. If you want CF to support NC_STRING attributes, please tell them and CC: NCO.
ncrename: WARNING "grid_mapping" attribute for variable /rainfall_amount is type NC_STRING, not NC_CHAR. This violates CF convention for specifying additional attributes. Therefore will skip this attribute. If you want CF to support NC_STRING attributes, please tell them and CC: NCO.
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco_rename_var()
nco_err_exit(): ERROR Error code is -101. Translation into English with nc_strerror(-101) is "NetCDF: HDF error"

---------------------------------------------------------------------------
NCOException                              Traceback (most recent call last)
<ipython-input-2-71c509e01436> in <module>()
      7 }
      8 for fname in glob('*.nc'):
----> 9     nco.ncrename(input=fname, options=[ Rename("variable", rDict) ])

/g/data/rr9/IM_PhD/projects/xa5/anaconda/lib/python2.7/site-packages/nco/nco.pyc in get(self, input, **kwargs)
    269                         return None
    270                     else:
--> 271                         raise NCOException(**retvals)
    272 
    273             if returnArray:

NCOException: (returncode:1) ncrename: INFO Extended filetype of MU-CLIM_WRF3-3-ERAInterim_rainfall-amount_hourly_05deg-SWWA_1981-2009_00000000_200712.nc is NC_FORMAT_HDF5, mode = 4097
ncrename: TIMER Metadata setup and file layout before main loop took    0.01 s
ncrename: CONVENTION File "Conventions" attribute is "CF-1.6"
ncrename: WARNING "coordinates" attribute for variable /rainfall_amount is type NC_STRING, not NC_CHAR. This violates CF convention for specifying additional attributes. Therefore will skip this attribute. If you want CF to support NC_STRING attributes, please tell them and CC: NCO.
ncrename: WARNING "coordinates" attribute for variable /landmask is type NC_STRING, not NC_CHAR. This violates CF convention for specifying additional attributes. Therefore will skip this attribute. If you want CF to support NC_STRING attributes, please tell them and CC: NCO.
ncrename: WARNING "grid_mapping" attribute for variable /rainfall_amount is type NC_STRING, not NC_CHAR. This violates CF convention for specifying additional attributes. Therefore will skip this attribute. If you want CF to support NC_STRING attributes, please tell them and CC: NCO.
ncrename: WARNING "coordinates" attribute for variable /rainfall_amount is type NC_STRING, not NC_CHAR. This violates CF convention for specifying additional attributes. Therefore will skip this attribute. If you want CF to support NC_STRING attributes, please tell them and CC: NCO.
ncrename: WARNING "coordinates" attribute for variable /landmask is type NC_STRING, not NC_CHAR. This violates CF convention for specifying additional attributes. Therefore will skip this attribute. If you want CF to support NC_STRING attributes, please tell them and CC: NCO.
ncrename: WARNING "grid_mapping" attribute for variable /rainfall_amount is type NC_STRING, not NC_CHAR. This violates CF convention for specifying additional attributes. Therefore will skip this attribute. If you want CF to support NC_STRING attributes, please tell them and CC: NCO.
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco_rename_var()
nco_err_exit(): ERROR Error code is -101. Translation into English with nc_strerror(-101) is "NetCDF: HDF error"


Thanks for your help Henry.
Ian

**Comment by hmb1** [comment]
HI Ian,
 not quite sure what to suggest.
Can you please try to run ncrename   from the command line (as above ) and see if it works ?
Thats:

`ncrename -v "latitude","lat" -v "longitude","lon" --nco_dbg_lvl=3 MU-CLIM_WRF3-3-ERAInterim_rainfall-amount_hourly_05deg-SWWA_1981-2009_00000000_200712.nc`

And see if it works
...Henry

**Comment by iMarang** [comment]
Hi Henry,

Sorry for the late reply.

I tried this at the command line:

ncrename -v "latitude","lat" -v "longitude","lon" --nco_dbg_lvl=3
ANUClimate_v1-1_solar-radiation_daily_0-01deg_1970-2014_00000000_201412.nc
ncrename: INFO Extended filetype of
ANUClimate_v1-1_solar-radiation_daily_0-01deg_1970-2014_00000000_201412.nc
is NC_FORMAT_HDF5, mode = 4097
ncrename: TIMER Metadata setup and file layout before main loop took
 0.01 s
ncrename: CONVENTION File "Conventions" attribute is "CF-1.6"
ncrename: Renamed variable '/latitude' to 'lat'
ncrename: Renamed 1 variable from 'latitude' to 'lat'
ncrename: Renamed variable '/longitude' to 'lon'
ncrename: Renamed 1 variable from 'longitude' to 'lon'
ncrename: In total renamed 0 attributes, 0 dimensions, 0 groups, and 2
variables
ncrename: TIMER Elapsed clock() time for command is    0.02 s

... variable rename works

ncrename -d "latitude","lat" -d "longitude","lon" --nco_dbg_lvl=3
ANUClimate_v1-1_solar-radiation_daily_0-01deg_1970-2014_00000000_201412.nc
ncrename: INFO Extended filetype of
ANUClimate_v1-1_solar-radiation_daily_0-01deg_1970-2014_00000000_201412.nc
is NC_FORMAT_HDF5, mode = 4097
ncrename: TIMER Metadata setup and file layout before main loop took
 0.02 s
ncrename: CONVENTION File "Conventions" attribute is "CF-1.6"
ncrename: Renamed dimension '/latitude' to 'lat'
ncrename: Renamed 1 dimension from 'latitude' to 'lat'
ncrename: Renamed dimension '/longitude' to 'lon'
ncrename: Renamed 1 dimension from 'longitude' to 'lon'
ncrename: In total renamed 0 attributes, 2 dimensions, 0 groups, and 0
variables
nco_err_exit(): ERROR Short NCO-generated message (usually name of function
that triggered error): nco_close()
nco_err_exit(): ERROR Error code is -101. Translation into English with
nc_strerror(-101) is "NetCDF: HDF error"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)

... dimension rename seems to work then dies.

And after running these two commands, when I try to ncdump -h on the same
file I get:

Segmentation fault

I've run both of the changes together and it seems to have worked on some
files and not others.  I'll do some more checking and confirm if I go down
the pynco route again.

Thanks for your help
Ian

**Comment by czender** [comment]
Renaming has been and is broken for use-cases like yours on netCDF4 files. This is likely a netCDF library bug not an NCO bug.
See http://nco.sf.net/nco.html#bug_nc4_rename
Suggest you convert to netCDF3 then rename then convert back.
