### ISSUE TITLE
libnetcdf.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by KarenGuihou** [nco/pynco#34]
Hi,

I am trying to run pynco on my debian machine, on a Conda environment.
I installed it by doing "conda install -c conda-forge pynco", but when I try to run some commands (such as "temperatures = nco.ncra(input=ifile, returnArray='T')", one of your examples), I get the following error:
/home/xxx/miniconda2/envs/python_env/bin/ncra: error while loading shared libraries: libnetcdf.so.7: cannot open shared object file: No such file or directory

When I do "ls /home/xxx/miniconda2/envs/python_env/lib", I have the following libnetcdf libs:
libnetcdf.a         libnetcdf.settings  libnetcdf.so        libnetcdf.so.13

here are the details about my install
Current conda install:

               platform : linux-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 2.7.14.final.0
       requests version : 2.18.4

Thank you!

**Comment by jhamman** [comment]
This seems like a conda problem, not a pynco problem. Chances are either conda/conda-forge is not installing libnetcdf correctly (not likely) or you have a competing environment variable (e.g. `LD_LIBRARY_PATH`). I suggest reporting upstream.

**Comment by KarenGuihou** [comment]
Ok, thank you, I will investigate then
