### ISSUE TITLE
ImportError: No module named custom

### ISSUE THREAD

**Issue by ValerioLembo** [nco/pynco#35]
Hi,

I am trying to include NCO commands into my Python scripts through Pynco package. 

I started to do some tests with basic manipulations of Netcdf files. Trying with "nco.rename" I used the syntax suggested in the WIki, i.e.:

```
rDict = {
    '.x': 'lon',
    '.y': 'lat'
}
nco.ncrename(input="tlcl.nc", options=[ c.Rename("tlcl", rDict) ])

```
But it returns an error saying that there is no global name called "c". I also tried to drop "c", but I got the same error with "Rename". 

I read here (https://github.com/nco/pynco/issues/30) that a module "custom" has to be imported. The question is, how to include it? The way it is suggested above gives me error:
"ImportError: No module named custom"

Is there a specific package that has to be included into the repository in order to obtain module "custom"?

Thanks in advance for the answer.

Best,

Valerio Lembo

**Comment by knaughten** [comment]
I made it work with

`from nco.custom import Limit`

since all I needed was Limit. So this should probably also work:

`import nco.custom as c`

**Comment by jhamman** [comment]
@ValerioLembo - is this still an issue that we should keep open? If so, please feel free to reopen.
