### ISSUE TITLE
Fix Travis Builds

### ISSUE THREAD

**Issue by jhamman** [nco/pynco#4]
Travis builds are failing and should be fixed

**Comment by jhamman** [comment]
All tests are passing when using NCO.4.5 locally so my bet is that there were some API changes between the version that `apt-get` gives (4.0) and 4.5.  I'll put together a PR that builds NCO from source and runs the test suite.

**Comment by ocefpaf** [comment]
@jhamman we have the latest [NCO](http://anaconda.org/ioos/nco) on the IOOS channel in case you want to try conda on your travis setup.

**Comment by jhamman** [comment]
Great idea!  Will try that first.

**Comment by jhamman** [comment]
I managed to fix the anaconda build on travis but there are still some failing tests. It would be great if someone could look over them and at least open an issue as to the specific failures.

**Comment by czender** [comment]
Thanks, Joe, for making all these updates. @hmb1 please post issues on any test failures you can reproduce.

**Comment by jhamman** [comment]
closed via #29
