### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jhamman** [nco/pynco#42]
Over the years, a number of users have reported problems using pynco on windows. I don't have a windows machine nor do I have any use for this library in a windows environment. That said, if someone wanted to add test support and any associated fixes, I'd be happy to accept a PR in this area.

xref: #15 #36

**Comment by FatAnorexic** [comment]
While I've never worked in this area, nor have any experience I can give it the old college try.

**Comment by ness31** [comment]
Hello could you please help me trying to concatenate netCDF files using pynco and ncrcat on windows ?
What is the pynco command for "ncrcat -p /datasets/ersst -n 1644,6,1,12,1,yyyymm ersst.v5.188001.nc -o ersst_all.nc"?
Thanks in advance

**Comment by hmb1** [comment]
HI Ness,
  To run pynco you need to have NCO commands in your  exec  path.  
  I suggest initially you try your command directly with NCO rather than through pynco.  

  I am not a Windows person; but a quick way to get going with NCO on windows is to install anaconda.  That way you don't have to actually build NCO on your local machine.

**Comment by jpcho89** [comment]
Thank you for your information.
I just solved the problem through Ubuntu linux operating system.

Jaepil
-------------------------------------------------------------------------------------------------------------
Jaepil Cho
Ph.D. / Director
Convergence Center for Watershed Management
Integrated Watershed Management Institute (IWMI)
202. 132, Ingye-ro, Paldal-gu, Suwon-si, Gyeonggi-do, 16489, Republic of
Korea
E-mail: jpcho89@gmail.com
Mobile: +82-10-5459-2455
Tel: +82-70-8860-4964
Fax: +82-31-8039-4964
Publications: http://scholar.google.co.kr/citations?user=zLyTfVIAAAAJ&hl=ko

**Comment by hmb1** [comment]
@ness31
This is how my code looks in LINUX:

 ```
   opt = [];
    opt+=[ "-Y ncrcat", '-p /datasets/ersst', '-n 1644,6,1,12,1,yyyymm' ]
    nco.ncra(input="ersst.v5.188001.nc",output="ersst_all.nc", options=opt )
```
You need the -Y option as Windows doesn't have the notion of symbolic links.
You also need the nco command in your PATH env var
...Henry

**Comment by S2021L** [comment]
Is there any pynco command for "ncks -v variablename in.nc out.nc"? This command is used to split a bigger .nc file to a smaller .nc file based on the variable name.

**Comment by czender** [comment]
@S2021L based on the above, try:
```
opt = [];
opt+=[ "-v variablename" ]
nco.ncks(input="in.nc",output="out.nc", options=opt )
```
@hmb1 does this look correct?

**Comment by czender** [comment]
This well-targeted initial issue has turned into a hodgepodge of help questions on unrelated issues. Closing.
