### ISSUE TITLE
options

### ISSUE THREAD

**Issue by dpath2o** [nco/pynco#49]
Curious how one gets the options input to work for ncks. 

My verified command-line code:
`ncwa -C -a lat,lon,time -d lon,-105,-100 -d lat,30,35 -l /tmp -p http://some.thredds.server/thredds/in.nc ~/out.nc`

My pynco command (run from python 3.7)
`nco.ncks( input = URLnc, output = Otmp, options = [ c.Limit("lat", minLt, maxLt),
                                                        c.Limit("lon", minLn, maxLn) ])`

The error:

> NameError: name 'c' is not defined

This is a rather obvious error, but the examples that I'm following on your page do not elaborate on the functionality here. I'm sure this is trivial.

Ultimately, what I want to do is extract netcdf information from a given lat,lon using NCO limits feature. Ideally I want to put this into pandas dataframe for quantitative analysis and time-series display.

Any help is appreciated.

**Comment by hmb1** [comment]
I think you need the following line at the top of your code page.
`import custom as c`

...Henry

**Comment by mifads** [comment]
Having the same problem with  name 'c' is not defined, and import custom as c didn't work either. conda install custom reports that this isn't available from current channels, and googling for python + custom returns 100s of useless sides. Which package is this? Thanks.

**Comment by hmb1** [comment]
@mifads
The file custom.py is  located in the nco directory. 
In the latest code in the pynco repo  nco.py is now NOT dependant  on this file.  
I shall try and get this code into the next conda build

**Comment by mifads** [comment]
Thanks. Look forward to the next version.
