### ISSUE TITLE
Initializing `Nco` with `overwrite=True` causes indefinite hang

### ISSUE THREAD

**Issue by lukelbd** [nco/pynco#56]
Using `Nco(overwrite=True)` causes an indefinite hang due to triggering a user-input prompt when subequently calling an nco command. Here's a simple example (see the attachment file):

```python
from nco import Nco
nco = Nco(overwrite=True)
nco.ncatted(input='tmp.nc', output='tmp.nc', options=['-a foo,ts,o,c,bar'])
```
[tmp.zip](https://github.com/nco/pynco/files/8593120/tmp.zip)

I tried printing `print(' '.join(cmd))` before the following line:

https://github.com/nco/pynco/blob/e17172c2a5f4c8b775eae8b8f63daea979929228/nco/nco.py#L332-L334

and the result was `ncatted -a ts,foo,o,c,bar --overwrite --overwrite --output=tmp.nc`. When I enter this in the command line after adding inputs with `ncatted -a ts,foo,o,c,bar --overwrite --overwrite tmp.nc --output=tmp.nc` I get the prompt:

```sh
(base) enceladus[1]:tmp$ ncatted -a ts,foo,o,c,bar --overwrite --overwrite tmp.nc --output=tmp.nc
ncatted: overwrite tmp.nc (y/n)?
```

So it seems a double overwrite flag triggers the input prompt, causing the infinite hang. I realize now `overwrite=True` isn't necessary since `Nco(force_output=True)` is the default, but this was hard to debug / could be a problem for others.

**Comment by mx-moth** [comment]
Looking at the ncatted source code, `--overwrite` will _toggle_ overwriting behaviour. Setting the flag twice results in overwrite being turned off again:

https://github.com/nco/nco/blob/1ad260bb1efad5ebf69fc4022435f9bd432d50ca/src/nco/ncatted.c#L353-L355

When overwrite is not enabled, the user is prompted whether a file should be overwritten. This prompt is never shown to the user as pynco collects the output, and the program appears to hang.

The hanging program issue can be solved by setting `stdin=subprocess.DEVNULL` when calling `subprocess.Popen()`. All `nco` tools will then try to read from stdin, not get any reply, and abort.

**Comment by czender** [comment]
Good catch @mx-moth! I just changed `--overwrite` from a toggle behavior to an absolute overwrite, throughout NCO. Now redundant switches will no longer cause hanging behavior because of upstream. (Yes, I also changed behavior of `--append`). We still need a volunteer to tag and release the latest PyNCO snapshot as v. 1.1 so people do not have to install PyNCO from source to get this fix!

**Comment by mx-moth** [comment]
I have another change or two in the works for `pynco` that I would like to be included in the next release, including a partial fix for the circumstances in this issue. Do you know who is in charge of releases for pynco?

**Comment by czender** [comment]
Great! The person nominally in charge (@hmb1) moved jobs and has not been active lately. I am happy to "bless" with commit priveleges anyone who understands the PyNCO code better than I do :) This includes you, if you are interested. LMK.

**Comment by mx-moth** [comment]
@czender I emailed you regarding helping out with the next release
