### ISSUE TITLE
Importing `distutils.spawn` raises DeprecationWarning

### ISSUE THREAD

**Issue by mx-moth** [nco/pynco#72]
`nco.nco` imports `distutils.spawn` so it can find the path to an executable. This now raises a DeprecationWarning. `disutils.spawn.find_executable` can be replaced with [`shutil.which()`](https://docs.python.org/3/library/shutil.html#shutil.which)

**Comment by czender** [comment]
Thanks @mx-moth. @hmb1 do you have time to create, test, and submit a PR with this change?

**Comment by czender** [comment]
I'll take that as a "No". I just pushed this change to the repository. Should probably make a new patch release. Will wait a few weeks to see if this change passes tests and does not cause any immediate problems for users.

**Comment by czender** [comment]
This change fails the self-test for py3.7 and succeeds on all later Python versions. Probably should eliminate the py37 test.

**Comment by czender** [comment]
Fixed by #73
