### ISSUE TITLE
Please release v1.1.1 and v1.1.2 on pypi.org

### ISSUE THREAD

**Issue by sharon-tickell** [nco/pynco#79]
This repository has v1.1.1 and v1.1.2 releases available from https://github.com/nco/pynco/releases which include the migration away from distutils which allows support for Python 3.12.   

Those releases are not yet available from pypi.org at https://pypi.org/project/nco/, but it would be nice if they were!

**Comment by czender** [comment]
Hi @sharon-tickell. Thank you for your suggestion. However, I'm a Python newbie who still relies on other for help with Python packaging. If someone helps, I would be glad to release those versions on pypi.org.

**Comment by mx-moth** [comment]
@czender Making releases to PyPI is automated through Github Actions for this repository. As an administrator of this repository you can make a PyPI release by:

* Navigate to the ["Actions" tab](https://github.com/nco/pynco/actions)
* Select the ["Publish a new version to PyPI" workflow](https://github.com/nco/pynco/actions/workflows/publish-to-pypi.yaml) in the sidebar
* Press the "Run workflow" dropdown button, and from the dropdown select the tag you want to publish to PyPI, then run the workflow.
* Wait for the workflow run to complete, then check PyPI to verify the release succeeded.

**Comment by czender** [comment]
Thanks for the clear instructions @mx-moth.
