### ISSUE TITLE
Consider renaming the package

### ISSUE THREAD

**Issue by ocefpaf** [nco/pynco#8]
Hi, I know that this is a terrible suggestion!  However, since the package is in its earlier stages maybe renaming it is not a big problem.

If you call the package `nco` it will create a confusing for packagers.  If you call it `nco-bindings` it is not very descriptive since it is about python bindings only.

I saw that you had `NCOpy` in the first release.  I like that, or infact anything similar like: `python-nco`, `pynco`, etc.  (Not ncopy though, that will read: n_copy :wink:)

Note that the module and how we import it does not have to change.

Thanks for the binding BTW!

**Comment by jhamman** [comment]
Thanks for the suggestion.  I agree the name of the package can be a bit difficult to discern.  `nco-bindings` was originally a fork from Ralf Mueller's [cdo-bindings](https://github.com/Try2Code/cdo-bindings) which provide python and ruby bindings to the cdo package.  I tried to keep the name the same.

I also agree that `python-nco` would be more descriptive and would consider that change.

**Comment by ocefpaf** [comment]
Thanks.  BTW I just created a conda package for it here:

https://binstar.org/IOOS/nco-bindings
https://github.com/ioos/conda-recipes/tree/master/nco-bindings
